library(dplyr)

df$categories_intentions <- df$categories_search + df$categories_find + df$categories_purchase
df <- df %>% select(-c(categories_search, categories_find, categories_purchase))


df$categories_religionandspirituality <- df$categories_atheismagnosticism + df$categories_buddhism + df$categories_christianity + df$categories_protestantism + df$categories_hinduism + df$categories_islam + df$categories_islamicfundamentalism
df <- df%>% select(-c(categories_protestantism, categories_hinduism, categories_islam, categories_islamicfundamentalism))


df$categories_shopping <- df$categories_shopping + df$categories_contestsandfreebies + df$categories_couponing + df$categories_comparisonsengines + df$categories_retail + df$categories_supermarkets + df$categories_secondhandmarket
df <- df %>% select(-c(categories_comparisonsengines, categories_retail, categories_supermarkets, categories_secondhandmarket))


df$categories_realestate <- df$categories_realestate + df$categories_apartments + df$categories_architects + df$categories_buyingsellinghomes
df <- df %>% select(-c(categories_realestate, categories_apartments, categories_architects, categories_buyingsellinghomes))


df$categories_travel <- df$categories_travel + df$categories_touristdestinations + df$categories_africa + df$categories_africa + df$categories_byuslocale + df$categories_canada + df$categories_europe + df$categories_france + df$categories_italy + df$categories_japan + df$categories_mexicoandcentralamerica + df$categories_southamerica + df$categories_unitedkingdom + df$categories_nationalparks + df$categories_themeparks + df$categories_cities + df$categories_spas + df$categories_seasideresorts + df$categories_skiresorts + df$categories_budgettravel + df$categories_lastminute + df$categories_holidays + df$categories_touristicfacilities + df$categories_bedandbreakfast + df$categories_camping + df$categories_hotel + df$categories_transports + df$categories_airtravel + df$categories_airplanes + df$categories_airfare + df$categories_airports + df$categories_airandspaceaccident + df$categories_railwayaccident + df$categories_railwaytravel + df$categories_roadtravel + df$categories_roadaccident + df$categories_seatravel + df$categories_cruises + df$categories_maritimeaccident + df$categories_publictransport

df <- df %>% select(-c(categories_travel, categories_touristdestinations, categories_africa, categories_africa, categories_byuslocale, categories_canada, categories_europe, categories_france, categories_italy, categories_japan, categories_mexicoandcentralamerica, categories_southamerica, categories_unitedkingdom, categories_nationalparks, categories_themeparks, categories_cities, categories_spas, categories_seasideresorts, categories_skiresorts, categories_budgettravel, categories_lastminute, categories_holidays, categories_touristicfacilities, categories_bedandbreakfast, categories_camping, categories_hotel, categories_transports, categories_airtravel, categories_airplanes, categories_airfare, categories_airports, categories_airandspaceaccident, categories_railwayaccident, categories_railwaytravel, categories_roadtravel, categories_roadaccident, categories_seatravel, categories_cruises, categories_maritimeaccident, categories_publictransport))


df$categories_technologyandcomputing <- df$categories_technologyandcomputing + df$categories_hardware + df$categories_computerperipherals + df$categories_monitor + df$categories_printers + df$categories_gameconsole + df$categories_disks + df$categories_graphicscards + df$categories_soundboard + df$categories_memory + df$categories_portablememory + df$categories_processors + df$categories_motherboards + df$categories_computernetworking + df$categories_router + df$categories_wirelesstechnology + df$categories_networksecurity + df$categories_computer + df$categories_desktopcomputer + df$categories_portablecomputer + df$categories_laptop + df$categories_palmtopspdas + df$categories_tabletpc + df$categories_internettechnology + df$categories_chat + df$categories_ecommerce + df$categories_email + df$categories_websearch + df$categories_forum + df$categories_socialnetwork + df$categories_computercrime + df$categories_hacking + df$categories_operatingsystems + df$categories_macos + df$categories_windows + df$categories_programminglanguages + df$categories_cc + df$categories_java + df$categories_javascript + df$categories_software + df$categories_antivirussoftware + df$categories_graphicssoftware + df$categories_3dgraphics + df$categories_sharewarefreeware + df$categories_desktopvideo + df$categories_databases + df$categories_technologicalinnovation + df$categories_consumerelectronics + df$categories_mp3reader + df$categories_ebookreader + df$categories_gpsnavigator + df$categories_homevideodvd + df$categories_radioset + df$categories_tvset + df$categories_camerasandcamcorders + df$categories_cameras + df$categories_camcorders + df$categories_photoandvideoaccessories + df$categories_telephony + df$categories_cellphones + df$categories_cellphoneaccessories + df$categories_connection + df$categories_fixedphone + df$categories_smartphone + df$categories_telephonerates + df$categories_electroniccomponents + df$categories_computerreviews + df$categories_macsupport + df$categories_mp3midi + df$categories_pcsupport

df <- df %>% select(-c(categories_technologyandcomputing, categories_hardware, categories_computerperipherals, categories_monitor, categories_printers, categories_gameconsole, categories_disks, categories_graphicscards, categories_soundboard, categories_memory, categories_portablememory, categories_processors, categories_motherboards, categories_computernetworking, categories_router, categories_wirelesstechnology, categories_networksecurity, categories_computer, categories_desktopcomputer, categories_portablecomputer, categories_laptop, categories_palmtopspdas, categories_tabletpc, categories_internettechnology, categories_chat, categories_ecommerce, categories_email, categories_websearch, categories_forum, categories_socialnetwork, categories_computercrime, categories_hacking, categories_operatingsystems, categories_macos, categories_windows, categories_programminglanguages, categories_cc, categories_java, categories_javascript, categories_software, categories_antivirussoftware, categories_graphicssoftware, categories_3dgraphics, categories_sharewarefreeware, categories_desktopvideo, categories_databases, categories_technologicalinnovation, categories_consumerelectronics, categories_mp3reader, categories_ebookreader, categories_gpsnavigator, categories_homevideodvd, categories_radioset, categories_tvset, categories_camerasandcamcorders, categories_cameras, categories_camcorders, categories_photoandvideoaccessories, categories_telephony, categories_cellphones, categories_cellphoneaccessories, categories_connection, categories_fixedphone, categories_smartphone, categories_telephonerates, categories_electroniccomponents, categories_computerreviews, categories_macsupport, categories_mp3midi, categories_pcsupport))
